# Generated by Django 4.2.5 on 2023-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarytransaction',
            name='fee',
        ),
        migrations.AlterField(
            model_name='librarymember',
            name='memid',
            field=models.CharField(max_length=10),
        ),
    ]
